M48
; DRILL file KiCad 10.0.6 date 2026-09-19T16:47:35
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-19T16:47:35+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X7.605Y-48.61
X7.605Y-54.39
T2
X3.0Y-37.5
X85.0Y-52.0
X250.0Y-3.2
X250.0Y-71.5
M30
